default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  timeout: 5000
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  host: localhost
  database: dhl_prototype_test

development:
  <<: *default
  host: localhost
  database: dhl_prototype_dev
